spring:
<<<<<<< HEAD
=======
  application:
    name: dentravak
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /health-check
        healthCheckInterval: 20s
---
spring:
>>>>>>> 76caca6e30da354b353ccac9418353dbe1bb91c6
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
<<<<<<< HEAD
      ddl-auto: update
=======
      ddl-auto: update
>>>>>>> 76caca6e30da354b353ccac9418353dbe1bb91c6
