version: '3'

services:
  consul:
    image: consul
    restart: unless-stopped
    ports:
      - 8500:8500

  den-travak:
    image: den-travak-app:0.0.1-SNAPSHOT
    restart: unless-stopped
    depends_on:
      - consul
    ports:
      - 8234:8080

  recommendation:
    image: recommendation-app:0.0.1-SNAPSHOT
    restart: unless-stopped
    depends_on:
      - consul
    ports:
      - 8235:8081